FROM python:3
ENV PYTHONUNBUFFERED=1

RUN \
    apt-get update && \
    apt-get -y install \
        libpq-dev \
        python-dev

WORKDIR /app

ADD     ./requirements.txt                   /app/
RUN     pip install -U pip
ADD     ./manage.py                          /app/

ADD     ./compose/django/start-dev.sh     /start-dev.sh

RUN     chmod +x /*.sh
